### ISSUE TITLE
Create first homework

### ISSUE THREAD

**Issue by taidanh** [taidanh/astr-119#3]

**Comment by ryarza** [comment]
Hi @taidanh,

Can you accept the pull request you made from first-homework to main? You linked the pull request to the issue, which is the right thing to do. Once you accept the pull request, the issue will be closed automatically. Please tag us again once you do that.

**Comment by ryarza** [comment]
Hi @taidanh,

You closed the pull request, which is equivalent to rejecting it. Can you reopen the pull request and accept it (i.e. merge the two branches)? Tag again after please.
